### ISSUE TITLE
Monitor off but not on again

### ISSUE THREAD

**Issue by codac** [grenagit/MMM-PIR-Sensor-Lite#3]
I am using your module on a Raspberry Pi 3 and a monitor that does not support CEC.
The monitor switches off but afterwards it remains black and wont turn back on, even if there is movement.

Here is my config:

```
                {
                        module: "MMM-PIR-Sensor-Lite",
                        position: "top_center",
                        config: {
                                sensorPin: 23, // GPIO pin
                                commandType: xrandr,
                                title: "Automatic Monitor Standby",
                                showCountDown: true,
                                showDetection: true,
                        }
                },

```

Any ideas how to fix that?

**Comment by grenagit** [comment]
@codac

What is the result of `lsb_release -r`? And `uname -a`?

What does using `xset` (`commandType : 'xset'` in your config)?

Does `xrandr --output HDMI-1 --rotate normal --auto` enable the monitor?

*Otherwise `commandType: xrandr,` is useless in your configuration because it is the default option!*

**Comment by codac** [comment]
`lsb_release -r` result:
`Release:        11`

`uname -a` result:
`Linux magicmirror 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux`

`xrandr --output HDMI-1 --rotate normal --auto`
does activate the monitor

I will change the value to xset and see what happens.

**Comment by codac** [comment]
sorry did not mean to close the issue yet..

**Comment by grenagit** [comment]
> I will change the value to xset and see what happens.

Has that solved the issue?

Did you [test your sensor](https://github.com/grenagit/MMM-PIR-Sensor-Lite#sensor-test) to see if it detected your presence?

**Comment by codac** [comment]
It seems that not the commands were the issue, but the screensaver that had to be switched off.
