### ISSUE TITLE
MMM-PIR-Sensor-Lite with MMM-RTSPStream

### ISSUE THREAD

**Issue by Laz2516** [grenagit/MMM-PIR-Sensor-Lite#5]
Good afternoon!

I understand that I have this special case, but maybe you will help...)

There is a problem with the [MMM-RTSPStream module](https://github.com/shbatm/MMM-RTSPStream). After turning off the screen with your module and then turning it on by the PIR sensor, the RTSP stream image is lost from the desired position on the screen.

Unfortunately, the author of MMM-RTSPStream no longer supports it.

> :warning: This module is no longer being actively developed. I will accept PRs and leave the repo active, but will not be directly supporting any issues. If anyone is interested in assuming ownership of the module, please contact @shbatm. :warning:

This problem occurs in many MM2 users. (I discussed this issue on the forum in various topics).
There is a curved way to return the image of the RTSP stream to the right place in the screen 
`pm2 restart /home/vova/MagicMirror/installers/mm.sh`

This command overloads the program MM2 and after rebooting the MM2, the video stream returns to the desired place in the RTSP frame. How can you add this command to your script or settings (make it disabled for other users who do not need to)?

Please help!

**Comment by grenagit** [comment]
Same answer as [here](https://forum.magicmirror.builders/post/104585):

> [MMM-RTSPStream](https://github.com/shbatm/MMM-RTSPStream) is no longer being actively developed 😐
So, I refer you to the advice of the author of [MMM-RTSPStream](https://github.com/shbatm/MMM-RTSPStream) to find another solution with WebRTC (newer and better standard) for example!

**Comment by Laz2516** [comment]
Unfortunately, this is too difficult and not suitable for everyone.
I don't have to change the way the video stream is displayed.
I found a way to recover the image. Let it be a crutch of course, but it works.

I am interested in how to add to the MMM-PIR-Sensor-Lite module the ability to reboot the MM2 program after the PIR sensor is triggered to move.
Reloading restores the correct RTSP flow mapping.

**Comment by Laz2516** [comment]
> to find another solution with WebRTC (newer and better standard) for example!

Unfortunately, I did not find such a module (WebRTC) for MM2 RTSP stream to work.
I am not a strong specialist in programming and raspberry... (
