### ISSUE TITLE
RPI4 xrand not off screen

### ISSUE THREAD

**Issue by cr4shydlo** [grenagit/MMM-PIR-Sensor-Lite#6]
Hello. I have Raspberry PI 4.

When i try to `xrandr --output HDMI-1 --off` : Monitor turn off.
When i test `PIR.py` i get info that pir is ok.
Counter go to 0 but screen not turn off.

**Comment by grenagit** [comment]
> When i test PIR.py i get info that pir is ok.

I assume that the sensor pin used for `python3 -u ~/MagicMirror/modules/MMM-PIR-Sensor-Lite/pir.py SENSOR_PIN` and the one shown in the module configuration are **the same**!

> Counter go to 0 but screen not turn off.

Strange! I added a few more logs to help with remote debugging on a new branch.

@cr4shydlo, can you :

1. Switch to the `debug-mode` branch:
```
cd ~/MagicMirror/modules/MMM-PIR-Sensor-Lite
git pull
git checkout debug-mode
```
2. Enable debug mode and reduce deactivate delay in module configuration with:
```
deactivateDelay: 10000,
debugMode: true,
```
3. Run MagicMirror in developper mode (with console):
```
cd ~/MagicMirror
npm run start:dev
```
4. Send the screenshot of your console as here:
![](https://github.com/grenagit/MMM-PIR-Sensor-Lite/raw/debug-mode/MMM-PIR-Sensor-Lite_console-log.png)

Thanks 👍

**Comment by cr4shydlo** [comment]
All works ok. I pull one more time plugin and reboot mirror. Thanks for help!

**Comment by grenagit** [comment]
> All works ok.

Good :+1:

@cr4shydlo, don’t forget to go back to the master branch:
```
cd ~/MagicMirror/modules/MMM-PIR-Sensor-Lite
git pull
git checkout master
```

**Comment by marcx28** [comment]
I have exactly the same issue. I did the steps above and this is a screenshot of the console output:

![screenshot_pir-sensor-lite](https://user-images.githubusercontent.com/35005352/211853903-521c9f47-cf26-47f7-a64b-b4e84c1b283f.png)
